### ISSUE TITLE
Feature request / workaround for passwords

### ISSUE THREAD

**Issue by hexxone** [goldfire/CanvasInput#24]
If I'm not missing something it's currently not possible to use the input type "password" or something similar to it, whereas it would be a great-to-have feature.

If you're not going to implement this, is there at least a quick workaround for it?

Thanks in advance.

**Comment by EddieOne** [comment]
You could intercept the input and store it somewhere while replacing the characters with \* the asterix symbol. This seems to be what browsers do. I don't have an example though.

**Comment by Fenel** [comment]
I suggest this workaround: https://github.com/noppa/text-security
