### ISSUE TITLE
How to Clear the Text?

### ISSUE THREAD

**Issue by EddieOne** [goldfire/CanvasInput#25]
This seems like it should be so easy.. How would I clear the text?

**Comment by EddieOne** [comment]
```
canvasInput._hiddenInput.value = '';
canvasInput._value = '';
canvasInput.blur();
```

**Comment by sunnyguan** [comment]
@EddieOne didn't work for me?

**Comment by sunnyguan** [comment]
@EddieOne Never mind, I added the code in the wrong place. Sorry :)
